# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/XilinxProjects/mtrxmlt_vrlg/mtrxmlt_vrlg.srcs/sources_1/ip/Matrix_A_1/Matrix_A.xci
# IP: The module: 'Matrix_A' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/XilinxProjects/mtrxmlt_vrlg/mtrxmlt_vrlg.srcs/sources_1/ip/Matrix_A_1/Matrix_A_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Matrix_A'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/XilinxProjects/mtrxmlt_vrlg/mtrxmlt_vrlg.srcs/sources_1/ip/Matrix_A_1/Matrix_A.xci
# IP: The module: 'Matrix_A' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/XilinxProjects/mtrxmlt_vrlg/mtrxmlt_vrlg.srcs/sources_1/ip/Matrix_A_1/Matrix_A_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Matrix_A'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
