# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/XilinxProjects/mtrxmlt_vrlg/mtrxmlt_vrlg.srcs/sources_1/ip/matrix_out/matrix_out.xci
# IP: The module: 'matrix_out' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/XilinxProjects/mtrxmlt_vrlg/mtrxmlt_vrlg.srcs/sources_1/ip/matrix_out/matrix_out_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'matrix_out'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/XilinxProjects/mtrxmlt_vrlg/mtrxmlt_vrlg.srcs/sources_1/ip/matrix_out/matrix_out.xci
# IP: The module: 'matrix_out' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/XilinxProjects/mtrxmlt_vrlg/mtrxmlt_vrlg.srcs/sources_1/ip/matrix_out/matrix_out_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'matrix_out'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
